import { StyleSheet } from 'react-native';
import { colors } from '../../theme';

export const h = StyleSheet.create({
  safe: { flex: 1, backgroundColor: '#005C3E' },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 8,
    paddingVertical: 9,
    gap: 4,
    backgroundColor: '#005C3E',
  },
  headerButton: {
    width: 40,
    height: 42,
    alignItems: 'center',
    justifyContent: 'center',
  },
  brand: { flex: 1 },
  unread: {
    position: 'absolute',
    top: 1,
    right: 2,
    minWidth: 17,
    height: 17,
    borderRadius: 9,
    backgroundColor: '#EF4761',
    alignItems: 'center',
    justifyContent: 'center',
  },
  unreadText: { color: '#FFFFFF', fontSize: 10, fontWeight: '700' },
  scroll: { flexGrow: 1, backgroundColor: '#FFFFFF', padding: 12 },
  content: { width: '100%', maxWidth: 720, alignSelf: 'center', gap: 13 },
  dateRow: { flexDirection: 'row', alignItems: 'center', gap: 7 },
  date: { fontSize: 13, fontWeight: '500', color: colors.ink },
  stats: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
  stat: {
    width: '48.4%',
    flexGrow: 1,
    borderRadius: 8,
    padding: 12,
    minHeight: 115,
    gap: 4,
  },
  statTop: { flexDirection: 'row', gap: 8, alignItems: 'center' },
  statTitle: { fontSize: 13, color: '#FFFFFF', flexShrink: 1 },
  statValue: {
    fontSize: 29,
    lineHeight: 37,
    color: '#FFFFFF',
    fontWeight: '700',
  },
  statValueSmall: { fontSize: 20, lineHeight: 28 },
  statSub: { fontSize: 11, color: '#FFFFFF', lineHeight: 18 },
  urgent: {
    borderWidth: 1,
    borderColor: '#F3E4E5',
    borderRadius: 7,
    overflow: 'hidden',
  },
  urgentTitle: {
    backgroundColor: '#FFE5E9',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  inline: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  urgentText: { fontSize: 15, fontWeight: '700', color: '#DC3C51' },
  viewAll: { fontSize: 12, color: '#DB3E56' },
  alertRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 9,
    minHeight: 38,
    paddingHorizontal: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#F3F5F3',
  },
  dot: { height: 11, width: 11, borderRadius: 6 },
  alertText: { fontSize: 12, color: colors.ink, flex: 1 },
  arrow: { fontSize: 23, color: colors.muted },
  emptyText: { fontSize: 12, color: colors.muted, padding: 10, lineHeight: 21 },
  quickGrid: { flexDirection: 'row', gap: 8 },
  quick: { flex: 1, alignItems: 'center', gap: 6 },
  quickIcon: {
    width: '100%',
    height: 61,
    borderRadius: 9,
    alignItems: 'center',
    justifyContent: 'center',
  },
  quickLabel: { fontSize: 11, color: colors.ink, textAlign: 'center' },
  vehicle: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  bus: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: '#F7F3DD',
    alignItems: 'center',
    justifyContent: 'center',
  },
  flex: { flex: 1, gap: 3 },
  name: { fontSize: 14, color: colors.ink, fontWeight: '700' },
  small: { fontSize: 11, color: colors.muted, lineHeight: 17 },
  greeting: { fontSize: 13, color: colors.ink },
  parentName: { fontSize: 19, fontWeight: '700', color: colors.ink },
  studentCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F5FBFF',
    gap: 10,
  },
  link: {
    fontSize: 13,
    color: colors.primary,
    fontWeight: '600',
    paddingVertical: 6,
  },
  vehiclePill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    alignSelf: 'center',
    backgroundColor: '#E4F5E5',
    paddingHorizontal: 15,
    paddingVertical: 4,
    borderRadius: 15,
    marginTop: -7,
  },
  vehiclePillText: { fontSize: 11, color: colors.primary },
  pressed: { opacity: 0.8 },
});
