import { StyleSheet } from 'react-native';
import { C } from './tokens';

export const s = StyleSheet.create({
  compactAvatar: { width: 34, height: 34, borderRadius: 17 },
  compactInitial: { fontSize: 17 },
  personListRow: { minHeight: 52, paddingVertical: 8 },
  avatarImage: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: C.mint,
  },
  studentColumn: { flex: 1.7 },
  driverColumn: { flex: 1.8 },
  semibold: { fontWeight: '600' },
  bold: { fontWeight: '700' },
  dangerFill: { backgroundColor: '#FFF0F2' },
  emergencyFill: { backgroundColor: '#FFE8ED' },
  warningFill: { backgroundColor: '#FFF4D9' },
  contactRow: { minHeight: 48 },
  contactIcon: { width: 32, height: 32, borderRadius: 16 },
  centered: { textAlign: 'center' },
  wrap: { flexWrap: 'wrap' },
  attendanceChoice: {
    width: 34,
    height: 36,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 6,
    borderWidth: 1,
  },
  choiceRow: { minHeight: 38 },
  checkbox: {
    width: 21,
    height: 21,
    borderRadius: 11,
    borderWidth: 1,
    borderColor: C.green,
    alignItems: 'center',
    justifyContent: 'center',
  },
  profit: {
    backgroundColor: C.green,
    borderRadius: 7,
    padding: 12,
    alignItems: 'center',
    gap: 3,
  },
  reportRow: { minHeight: 40 },
  safe: { flex: 1, backgroundColor: C.background },
  page: { padding: 12, gap: 11, paddingBottom: 24 },
  box: {
    borderRadius: 9,
    borderWidth: 1,
    borderColor: C.line,
    backgroundColor: C.white,
    padding: 12,
    gap: 10,
  },
  row: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  compactActions: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  between: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  flex: { flex: 1 },
  stack: { gap: 8 },
  title: { fontSize: 16, fontWeight: '700', color: C.text },
  heading: { fontSize: 15, color: C.green, fontWeight: '700' },
  body: { fontSize: 13, lineHeight: 20, color: C.text },
  muted: { fontSize: 12, lineHeight: 18, color: C.muted },
  green: { color: C.green },
  red: { color: C.red },
  amber: { color: C.amber },
  white: { color: C.white },
  button: {
    minHeight: 40,
    borderRadius: 7,
    backgroundColor: C.green,
    paddingHorizontal: 11,
    paddingVertical: 8,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 5,
  },
  iconButton: {
    width: 38,
    height: 38,
    borderRadius: 19,
    borderWidth: 1,
    borderColor: C.line,
    backgroundColor: C.mint,
    alignItems: 'center',
    justifyContent: 'center',
  },
  buttonText: {
    fontSize: 12,
    lineHeight: 19,
    color: C.white,
    fontWeight: '600',
    flexShrink: 1,
  },
  secondary: { backgroundColor: C.mint },
  dangerButton: { backgroundColor: C.red },
  dim: { opacity: 0.55 },
  error: { padding: 10, borderRadius: 7, backgroundColor: '#FFF0F2' },
  errorText: { color: '#A3203E', fontSize: 13, lineHeight: 20 },
  empty: { alignItems: 'center', padding: 25, gap: 9 },
  pill: {
    backgroundColor: '#DBF6E5',
    paddingVertical: 4,
    paddingHorizontal: 9,
    borderRadius: 15,
    alignSelf: 'flex-start',
  },
  pillBad: { backgroundColor: '#FFE6EB' },
  pillPending: { backgroundColor: '#FFF2D8' },
  pillText: { color: C.green, fontSize: 11, fontWeight: '600' },
  avatar: {
    width: 43,
    height: 43,
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#E1F0F7',
  },
  driverAvatar: { backgroundColor: '#E3F2E6' },
  initial: { color: C.green, fontSize: 21, fontWeight: '700' },
  search: {
    flex: 1,
    minHeight: 42,
    borderWidth: 1,
    borderColor: C.line,
    borderRadius: 7,
    backgroundColor: C.white,
    flexDirection: 'row',
    alignItems: 'center',
    paddingLeft: 10,
    gap: 7,
  },
  searchInput: { flex: 1, color: C.text, fontSize: 12, padding: 7 },
  tabs: {
    flexDirection: 'row',
    padding: 3,
    borderRadius: 7,
    backgroundColor: '#EDF3F7',
    gap: 3,
  },
  tab: {
    flex: 1,
    minHeight: 38,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 6,
    borderRadius: 6,
  },
  tabActive: { backgroundColor: C.green },
  tabLabel: {
    fontSize: 12,
    color: C.text,
    fontWeight: '600',
    textAlign: 'center',
  },
  field: { gap: 5 },
  fieldLabelRow: {
    minHeight: 28,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  label: { fontSize: 12, color: C.text, fontWeight: '600' },
  input: {
    backgroundColor: C.white,
    borderWidth: 1,
    borderColor: C.line,
    borderRadius: 7,
    minHeight: 44,
    paddingHorizontal: 11,
    paddingVertical: 9,
    color: C.text,
    fontSize: 14,
  },
  invalid: { borderColor: '#A3203E', borderWidth: 2 },
  multiline: { minHeight: 90, textAlignVertical: 'top' },
  select: {
    backgroundColor: C.white,
    borderWidth: 1,
    borderColor: C.line,
    borderRadius: 7,
    overflow: 'hidden',
  },
  picker: { minHeight: 44, color: C.text },
  detail: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 7,
    paddingVertical: 5,
  },
  detailLabel: { fontSize: 12, color: C.text, flex: 1 },
  detailValue: {
    color: C.text,
    fontSize: 13,
    fontWeight: '500',
    maxWidth: '63%',
    textAlign: 'right',
  },
  linkHit: { minHeight: 38, justifyContent: 'center' },
  link: { fontSize: 12, color: C.green, fontWeight: '600' },
  modalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: C.dark,
    paddingRight: 12,
    minHeight: 54,
  },
  back: {
    width: 48,
    minHeight: 48,
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalTitle: { color: C.white, fontSize: 18, fontWeight: '600' },
  form: { padding: 16, gap: 14, paddingBottom: 35 },
  line: { height: 1, backgroundColor: C.line },
  tableRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 7,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#EFF3F4',
  },
  tableHeader: {
    backgroundColor: '#F0F5F8',
    borderRadius: 5,
    paddingHorizontal: 6,
    paddingVertical: 8,
    flexDirection: 'row',
    gap: 7,
  },
  cell: { flex: 1, fontSize: 11, color: C.text },
  smallCell: { width: 65, fontSize: 11, color: C.text },
  summary: {
    flex: 1,
    borderRadius: 7,
    backgroundColor: C.mint,
    padding: 10,
    gap: 5,
  },
  summaryValue: { color: C.green, fontWeight: '700', fontSize: 20 },
  listTouch: { minHeight: 62 },
  note: {
    color: C.green,
    backgroundColor: C.mint,
    borderRadius: 7,
    padding: 10,
    fontSize: 12,
    lineHeight: 19,
  },
});
