import { StyleSheet } from 'react-native';
import { colors } from '../../theme';

export const local = StyleSheet.create({
  tabs: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 4,
    padding: 3,
    borderRadius: 7,
    backgroundColor: '#EEF5F2',
  },
  tab: {
    flexGrow: 1,
    flexBasis: 90,
    minHeight: 44,
    paddingHorizontal: 7,
    paddingVertical: 8,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 6,
    backgroundColor: 'transparent',
  },
  selectedTab: { backgroundColor: colors.primary, borderColor: colors.primary },
  guardianTab: { flexBasis: '40%', flexDirection: 'row', gap: 8 },
  tabText: {
    flexShrink: 1,
    color: colors.ink,
    fontSize: 13,
    lineHeight: 19,
    fontWeight: '600',
    textAlign: 'center',
  },
  selectedTabText: { color: colors.surface },
  section: { gap: 9 },
  card: {
    padding: 12,
    gap: 6,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.line,
    borderRadius: 8,
  },
  cardHeader: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  cardTitle: {
    flexGrow: 1,
    flexShrink: 1,
    flexBasis: 160,
    color: colors.ink,
    fontSize: 15,
    lineHeight: 22,
    fontWeight: '700',
  },
  body: { color: colors.ink, fontSize: 14, lineHeight: 21 },
  actions: {
    marginTop: 4,
    borderTopWidth: 1,
    borderTopColor: colors.line,
  },
  disclosure: {
    minHeight: 44,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  link: {
    color: colors.primary,
    fontSize: 14,
    fontWeight: '600',
    flexShrink: 1,
  },
  actionFields: { gap: 12, paddingTop: 4 },
  hidden: { display: 'none' },
  pressed: { opacity: 0.7 },
});
