import { StyleSheet } from 'react-native';
import { colors } from '../../theme';

export const local = StyleSheet.create({
  reviewNote: { padding: 10, borderRadius: 7, backgroundColor: colors.mint },
  reviewNoteError: { backgroundColor: '#FBEAEC' },
  reviewNoteErrorText: { color: colors.danger },
  stepper: { flexDirection: 'row', paddingVertical: 5 },
  step: { flex: 1, alignItems: 'center', gap: 7 },
  stepTop: {
    flexDirection: 'row',
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  stepCircle: {
    width: 29,
    height: 29,
    borderRadius: 15,
    borderWidth: 1,
    borderColor: colors.line,
    backgroundColor: '#EDF1EF',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 1,
  },
  stepCircleActive: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
  },
  stepNumber: { color: colors.muted, fontSize: 14, fontWeight: '700' },
  stepNumberActive: { color: '#FFFFFF' },
  stepLabel: {
    color: colors.muted,
    fontSize: 10,
    lineHeight: 15,
    textAlign: 'center',
    maxWidth: 70,
  },
  stepLabelActive: { color: colors.primary, fontWeight: '700' },
  connector: { height: 2, backgroundColor: '#DDE7E1', flex: 1 },
  connectorDone: { backgroundColor: colors.primary },
  connectorEdge: { opacity: 0 },
  photoRow: {
    flexDirection: 'row',
    gap: 16,
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  photoPicker: {
    backgroundColor: '#F5FAFF',
    borderWidth: 1,
    borderColor: colors.line,
    flex: 1,
    minHeight: 84,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 7,
    gap: 6,
  },
  routeCard: {
    flexDirection: 'row',
    gap: 10,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: colors.line,
    borderRadius: 8,
    backgroundColor: '#FFFFFF',
    padding: 13,
    minHeight: 75,
  },
  routeSelected: { borderColor: colors.primary, backgroundColor: '#F0FAF5' },
  routeFare: { color: colors.ink, fontSize: 15, fontWeight: '700' },
  radio: {
    height: 20,
    width: 20,
    borderRadius: 10,
    borderWidth: 1.5,
    borderColor: '#ABBAB2',
    justifyContent: 'center',
    alignItems: 'center',
  },
  radioSelected: { borderColor: colors.primary },
  radioDot: {
    height: 10,
    width: 10,
    borderRadius: 5,
    backgroundColor: colors.primary,
  },
  rejected: { backgroundColor: colors.danger },
  vehicleIcon: {
    backgroundColor: colors.primary,
    width: 46,
    height: 46,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  stale: { color: '#98701F', fontSize: 12, lineHeight: 19 },
});
