export type HomeStackParams = {
  Fleet: undefined;
  CreateVehicle: undefined;
  Students: undefined;
  StudentDetails: { id: string };
  Bills: { billId?: string; paymentId?: string } | undefined;
  DueList: undefined;
  Requested: { id?: string } | undefined;
  Complaints: { id?: string } | undefined;
  StopRequests: { id?: string } | undefined;
  PaymentAccounts: undefined;
  Vehicles: undefined;
  VehicleDetails: { id: string };
  FleetMap: undefined;
  Routes: undefined;
  RouteDetails: { id: string };
  Inbox: undefined;
  NotificationDetails: { id: string };
  VehicleHistory: { imei: string; name: string };
  More: undefined;
  Receipts: undefined;
  Drivers: undefined;
  DriverDetails: { id: string };
  Attendance: undefined;
  Maintenance: { vehicleId?: string } | undefined;
  Accounts: { tab?: 'INCOME' | 'EXPENSE' | 'INVESTMENT' } | undefined;
  Notices: undefined;
  OperationalRequests: { id?: string } | undefined;
  Communication: undefined;
  Reports: undefined;
  Settings: undefined;
  ParentProfile: { id?: string } | undefined;
  Admission: { studentId?: string } | undefined;
  ApplicationStatus: { id?: string } | undefined;
  TodayJourney: undefined;
  Contact: undefined;
  LiveTracking: { vehicleId?: string } | undefined;
  Emergency: undefined;
};
