import { StyleSheet } from 'react-native';
import { colors } from '../../theme';

export const f = StyleSheet.create({
  toolbar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  searchToolbar: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  searchBox: {
    flex: 1,
    minHeight: 44,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingLeft: 12,
    paddingRight: 4,
    borderWidth: 1,
    borderColor: colors.line,
    borderRadius: 8,
    backgroundColor: '#FFFFFF',
  },
  searchInput: {
    flex: 1,
    minHeight: 42,
    paddingVertical: 8,
    color: colors.ink,
    fontSize: 14,
  },
  mapButton: {
    width: 42,
    height: 42,
    borderRadius: 21,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.mint,
    borderWidth: 1,
    borderColor: colors.line,
  },
  pressed: { opacity: 0.8, transform: [{ scale: 0.96 }] },
  list: { padding: 0, overflow: 'hidden' },
  vehicleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 11,
    padding: 11,
    borderBottomWidth: 1,
    borderBottomColor: colors.line,
  },
  vehicleMark: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: '#F6F2DD',
    alignItems: 'center',
    justifyContent: 'center',
  },
  flex: { flex: 1, gap: 3 },
  title: { fontSize: 16, color: colors.ink, fontWeight: '700' },
  sub: { fontSize: 12, lineHeight: 20, color: colors.muted },
  detail: { flexDirection: 'row', alignItems: 'center', gap: 8, minHeight: 33 },
  detailLabel: { flex: 1, fontSize: 13, color: colors.ink, lineHeight: 21 },
  detailValue: { flex: 1, fontSize: 13, color: colors.ink, textAlign: 'right' },
  iconButton: {
    height: 42,
    width: 36,
    alignItems: 'center',
    justifyContent: 'center',
  },
  actionRow: { flexDirection: 'row', gap: 8, alignItems: 'center' },
  routeMark: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  arrow: { fontSize: 23, color: colors.muted },
  period: {
    flex: 1,
    padding: 8,
    alignItems: 'center',
    borderRadius: 5,
    backgroundColor: '#F0F6F2',
  },
  periodSelected: { backgroundColor: colors.primary },
  white: { fontSize: 13, color: '#FFFFFF' },
  tableHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F0F8F4',
    padding: 9,
    gap: 8,
  },
  number: { width: 25, fontSize: 12, color: colors.ink },
  tableRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 10,
    paddingHorizontal: 9,
    gap: 8,
    borderBottomWidth: 1,
    borderBottomColor: colors.line,
  },
  bold: { fontWeight: '700' },
  scheduleEdit: {
    gap: 8,
    borderBottomWidth: 1,
    borderBottomColor: colors.line,
    paddingBottom: 12,
  },
  remove: { fontSize: 29, color: colors.danger, padding: 8 },
});
